### ISSUE TITLE
Support for Oral-B Pro 6200

### ISSUE THREAD

**Issue by hnrkp** [Bluetooth-Devices/oralb-ble#16]
Currently the Oral-B Pro 6200 is not supported. I have one of these. I've captured a pcap of the BTLE traffic and a few years ago I wrote some decoder that's now lost somewhere, but I know it's possible to support it at least. It supports five modes but no sector detection.

I haven't played around with developing or debugging integrations or their dependencies for Home Assistant but I know Python and might be able to hack something together if I find some time. But also maybe someone already up to speed can take my pcap and give it a quick look to see if the implementation is trivial? If not, some pointers to how to best develop and test something (under Linux, or maybe the docker thing) are welcome.

**Comment by hnrkp** [comment]
[capture.zip](https://github.com/Bluetooth-Devices/oralb-ble/files/9939411/capture.zip)

Capture of some seconds cycling up and modes stepped through.

**Comment by bdraco** [comment]
If you turn on debug logs for homeassistant.components.bluetooth you will get the AdvertisementData.  That’s what we need to add new devices

**Comment by hnrkp** [comment]
[oralb-pro-6200-ha.txt](https://github.com/Bluetooth-Devices/oralb-ble/files/9939896/oralb-pro-6200-ha.txt)

Here you go.

**Comment by dannytsang** [comment]
@bdraco My Oral-B works with Smart 6 - 6000N reports the following pressure numbers:
* normal: 50
* high: 242

**Comment by bdraco** [comment]
@dannytsang Thanks.  I'll add those mappings

**Comment by bdraco** [comment]
@hnrkp It looks like the 6200 has a completely different format but it should be supportable.  

You'll need to provide an explanation of what the toothbrush is doing for each Advertisment so we can build a mapping.

**Comment by bdraco** [comment]
@dannytsang Can you post your `AdvertisementData` as well to compare?

**Comment by dannytsang** [comment]
@bdraco here's mine. I went through all the modes I had and did a pressure test on the whitening mode which didn't change the pressure value.

[6000N BT advertisement.log](https://github.com/Bluetooth-Devices/oralb-ble/files/9944724/6000N.BT.advertisement.log)

Let me know if you need any more.

**Comment by bdraco** [comment]
Thanks. I'll add tests for thoose

**Comment by hnrkp** [comment]
Tested with latest dev (which was oralb-ble 0.13.0) and it seems to work well with my 6200. Great work!
