### ISSUE TITLE
Genius 8000 Support

### ISSUE THREAD

**Issue by greghesp** [Bluetooth-Devices/oralb-ble#20]
As per https://github.com/home-assistant/core/issues/81594

I have a Genius 8000, which is not on the supported list according to the documentation, however, I can confirm it works with some missing info. It's also showing as a smarter series 7000.

**AdvertisementData**
`2022-11-06 08:02:34.946 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] 00:1A:7D:DA:71:15: 58:7A:62:41:59:7F AdvertisementData(local_name='Oral-B Toothbrush', manufacturer_data={220: b'\x03"\x0c\x02 \x00\x00\x01\x01\x00\x04'}, rssi=-77) connectable: True match: {'oralb'} rssi: -77`

`2022-11-06 08:03:17.402 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] 00:1A:7D:DA:71:15: 58:7A:62:41:59:7F AdvertisementData(local_name='Oral-B Toothbrush', manufacturer_data={220: b'\x03"\x0c\x02 \x00\r\x03\x01+\x04'}, rssi=-76) connectable: True match: set() rssi: -76`

`2022-11-06 11:20:05.828 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] 00:1A:7D:DA:71:15: 58:7A:62:41:59:7F AdvertisementData(local_name='Oral-B Toothbrush', manufacturer_data={220: b'\x03"\x0c\x02 \x00\x00\x03\x01\x00\x04'}, rssi=-73) connectable: True match: set() rssi: -73`

`2022-11-06 11:20:28.476 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] 00:1A:7D:DA:71:15: 58:7A:62:41:59:7F AdvertisementData(local_name='Oral-B Toothbrush', manufacturer_data={220: b'\x03"\x0c\x03\x00\x00\x0b\x07\x01$\x04'}, rssi=-80) connectable: True match: set() rssi: -80`

`2022-11-06 11:21:10.786 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] 00:1A:7D:DA:71:15: 58:7A:62:41:59:7F AdvertisementData(local_name='Oral-B Toothbrush', manufacturer_data={220: b'\x03"\x0c\x03\x00\x005\x07\x02L\x04'}, rssi=-76) connectable: True match: set() rssi: -76`

`2022-11-06 11:22:32.132 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] 00:1A:7D:DA:71:15: 58:7A:62:41:59:7F AdvertisementData(local_name='Oral-B Toothbrush', manufacturer_data={220: b'\x03"\x0c\x02 \x02\x03\x07\x0f\n\x04'}, rssi=-76) connectable: True match: set() rssi: -76`

**Comment by bdraco** [comment]
What value does pressure report when you have normal and high pressure ?
