### ISSUE TITLE
Add support for Oral-B iO 10 

### ISSUE THREAD

**Issue by Mitch73-2** [Bluetooth-Devices/oralb-ble#45]
** Feature request

Today I purchased an Oral-B iO series 10 White and wanted to add it to HA but it turns out that support only goes up to iO series 9. 
Is there any prospect when iO series 10 is added?
<img width="352" alt="Scherm­afbeelding 2024-01-13 om 11 19 31" src="https://github.com/Bluetooth-Devices/oralb-ble/assets/76648341/e7a4e585-3caf-4ac6-9f6a-9f7a5cf838e8">

Added some data `AdvertisementData(local_name='Oral-B Toothbrush', manufacturer_data={220: b'\x062k\x03r\x00\x00\x06\x00\x00\x01'}, service_uuids=['0000fe0d-0000-1000-8000-00805f9b34fb'], tx_power=0, rssi=-61) match: set()`

**Comment by ebertek** [comment]
The hockey puck communicates with some remote server using Secure MQTT; might there be some way to intercept these messages and just skip using Bluetooth altogether?

**Comment by alvinchen1** [comment]
@ebertek, not a bad idea, but sounds like that might be something for a different method of integration via Secure MQTT vs Bluetooth which is the primary method of integration for this organization/repository.  I did some digging and apart from some fancy stuff the io series 10 does in that hocky puck, it appears to have the same functionality as the io Series 9.  Should at a minimum have the similar functionality to the 9, and maybe we will see some additional functionality we can open up once we get it integrated with HA.

**Comment by Robert7997** [comment]
Hi all,

I recently upgraded from an older Oral-B model to the Oral-B iO10 with iO Sense charger, expecting improved Home Assistant integration and access to more brushing metrics.

The official Home Assistant Oral-B integration successfully discovers the toothbrush and exposes the following entities:

Status (charging, selection_menu, etc.)
Battery level
Brushing mode
Pressure state
Number of sectors
However, the most interesting data available in the Oral-B app does not appear to be exposed through Home Assistant:

Brushing session duration
Coverage / brushing zone completion
Detailed sector progress
Pressure statistics
Historical brushing results
Coverage percentages (Inside / Outside / Chewing surfaces)
In the Oral-B app these metrics are available immediately after brushing, but Home Assistant only seems to receive a limited subset of information.

My questions are:

Is this a limitation of the current BLE decoder?
Does the iO10 expose additional data that is currently not parsed by Home Assistant?
Is any data available through the iO Sense WiFi charger or Oral-B cloud APIs?
Would support for iO10/iO Sense be a useful future enhancement for the Oral-B integration?
I'd be happy to assist with testing and provide BLE advertisements, logs, or packet captures if needed.

Thanks for all the work on the integration.

Note:
Model: Oral-B iO10
Home Assistant OS
Core: 2026.6.0
Supervisor: 2026.05.1
OS: 17.3
Frontend: 20260527.4
Bluetooth integration: Official Oral-B integration
Observed entities:

status
battery
brushing mode
pressure
number_of_sectors
Missing:

session duration
coverage
zone statistics
pressure history
